[package]
name = "cuickcook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
async-openai = "0.20.0"
dotenvy = "0.15.7"
rusty_dl = "1.0.8"
serde = "1.0.198"
